export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const FILL_PERIKOPENS = 'FILL_PERIKOPENS';
export const READ_PERIKOPEN = 'READ_PERIKOPEN';
export const GET_PERIKOPEN = 'GET_PERIKOPEN';
export const GET_LAST_READ_PERIKOPEN = 'GET_LAST_READ_PERIKOPEN';
export const INIT_PERIKOPEN = 'INIT_PERIKOPEN';
export const GET_TODAY_PERIKOPEN = 'GET_TODAY_PERIKOPEN';
export const SET_TODAY_PERIKOPEN = 'SET_TODAY_PERIKOPEN';
export const SET_ACTIVE_PERIKOPEN = 'SET_ACTIVE_PERIKOPEN';

export const APP_VERSION_CODE = '0.3.1';
export const APP_VERSION_NUMBER = 11;
